apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80              # Port inside the cluster (container port)
      targetPort: 80        # Port your frontend app listens on
      nodePort: 30080       # External port exposed on nodes
