name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Authenticate to Google Cloud
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_CREDENTIALS }}'
        token_format: 'access_token'

    # Setup gcloud CLI with GKE auth plugin
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        install_components: 'gke-gcloud-auth-plugin'

    # Configure Docker to use gcloud as a credential helper for Artifact Registry
    - name: Authenticate Docker to Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GKE_REGION }}-docker.pkg.dev --quiet

    - name: Build and push backend image to Artifact Registry
      run: |
        docker build -t ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/backend/backend:latest ./backend
        docker push ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/backend/backend:latest

    - name: Build and push frontend image to Artifact Registry
      run: |
        docker build -t ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/frontend/frontend:latest ./frontend
        docker push ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/frontend/frontend:latest

    # Configure kubectl with GKE auth plugin enabled
    - name: Configure kubectl
      env:
        USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

    # Update deployments with GKE auth plugin enabled
    - name: Update backend deployment
      env:
        USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      run: |
        kubectl rollout restart deployment backend

    - name: Update frontend deployment
      env:
        USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      run: |
        kubectl rollout restart deployment frontend
