name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GKE_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate Docker to Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GKE_REGION }}-docker.pkg.dev

    - name: Build and push backend image to Artifact Registry
      run: |
        docker build -t ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/backend/backend:latest ./backend
        docker push ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/backend/backend:latest

    - name: Build and push frontend image to Artifact Registry
      run: |
        docker build -t ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/frontend/frontend:latest ./frontend
        docker push ${{ secrets.GKE_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/frontend/frontend:latest

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

    - name: Apply backend Kubernetes manifests
      run: |
        kubectl apply -f backend/

    - name: Apply frontend Kubernetes manifests
      run: |
        kubectl apply -f frontend/
